n = input('Digite alguma coisa:')
print('o tipo primitivo desse valor é', type(n, ))
print('so tem espaço?', n.isspace())
print('É um numero?', n.isnumeric())
print('É alfabetico?', n.isalpha())
print('É alfanumerico?', n.isalnum())
print('Ésta em maisculas?', n.isupper())
print('esta em minusculas?', n.islower())
print('esta capitalizada?', n.istitle())